### ISSUE TITLE
Feature Request: Jump to certain position in queue

### ISSUE THREAD

**Issue by bayerlse** [chrisweb/web-audio-api-player#25]
## Expected behavior and improvement this new feature would bring

When the user wants to play a certain file at a certain position, the API doesn't allow this easily.
Imagine a list of timelines for all audios in a queue, where the user can choose which sound to play at which position.

Maybe this could be easily integrated in: `setPositionInSeconds` (or `setPosition`)

via adding an id parameter: `player.setPositionInSeconds(seconds, index)`

which can be then handled in: https://github.com/chrisweb/web-audio-api-player/blob/4a53dbbe15e1ba4419d4abee8c6c43d2e15476dd/src/library/core.ts#L312 

But thanks for this awesome lib, really like it!

Greets, Sebi

**Comment by chrisweb** [comment]
Hello Sebi

Glad you like it :)

Hmmm, it would probably not be too hard to add the feature you mention... I need to think about this

I guess I would not use setPositionInSeconds, because the play() method of the player already allows today to define which sound will get played and also at which position, but not by queue index, if you use the parameter **whichSound** the options you have today are to leave it undefined (which will play the current sound if there is a current pointer or else the first sound in the queue) or you can set it to a song ID or use a constant to play the PREVIOUS, NEXT, FIRST or LAST song

so if you use it like this:

```
        // initialize
        const player = new PlayerCore()
        // add two sounds
        const firstSoundAttributes = {
            source: [
                {
                    url: 'mp3/song1.mp3',
                    codec: 'mp3',
                }
            ],
            id: 1,
        }
        const firstSound = player.addSoundToQueue({ soundAttributes: firstSoundAttributes })
        const secondSoundAttributes = {
            source: [
                {
                    url: 'mp3/song1.mp3',
                    codec: 'mp3',
                }
            ],
            id: 2,
        }
        const secondSound = player.addSoundToQueue({ soundAttributes: secondSoundAttributes })
        // play the second song
        player.play({ whichSound: 2, playTimeOffset: 10 })
```

it will play the second sound and start playing at 10 seconds

now if you want to play songs by queue index, you could already do this today by maintaining your own queue:

```
        // create your own queue
        const myPlaylistQueue = []
        // initialize
        const player = new PlayerCore()
        // add two sounds
        const firstSoundAttributes = {
            source: [
                {
                    url: 'mp3/song1.mp3',
                    codec: 'mp3',
                }
            ],
            id: 1,
        }
        const firstSound = player.addSoundToQueue({ soundAttributes: firstSoundAttributes })
        myPlaylistQueue.push(firstSound)
        const secondSoundAttributes = {
            source: [
                {
                    url: 'mp3/song1.mp3',
                    codec: 'mp3',
                }
            ],
            id: 2,
        }
        const secondSound = player.addSoundToQueue({ soundAttributes: secondSoundAttributes })
        myPlaylistQueue.push(secondSound)
        // play the second sound using my own queue index
        const soundByIndex = myPlaylistQueue[1]
        player.play({ whichSound: soundByIndex.id })
```

As I said I could add a "play by queue index" feature, but I wonder if the developer always knows what the index of a song is, because there are a lot of cases where it might not be obvious to know the index, for example if you add 3 sounds but then remove the first sound, is the queue index for the second sound now 0 or 1, or imagine the case where a user is playing a song on page, the sond index in the queue is 0, but then the user navigates to a second page with a playlist that has two songs, now you add the two songs to the playlist, because the previous song is still playing the two songs of the playlist will have the index 1 and 2, which means if you want to tell the player to switch to the first song of the playlist you would need call play 1 and not play 0 (the playlist on the screen has two songs but the player queue currently has 3 songs) 

Also I just realized that I have no documentation listing all the player methods, I just created a ticket for myself and will try to do this soon: https://github.com/chrisweb/web-audio-api-player/issues/26

**Comment by chrisweb** [comment]
I worked on major new 5.1.0 release during the last 7 days, in that release there are a bunch of improvements to the documentation and also an improved example, here is the full changelog: https://github.com/chrisweb/web-audio-api-player/releases/tag/5.1.0

The example now has buttons, "play song by ID" as well as" play song by ID and an offset", I hope this demonstrates how to use the player.play() function to play a certain song at a certain position, as I mentioned before the setPosition is more to change the position when the song is already playing, if used to move the position in combination with a play() it would create a small delay where the song starts and then the position changes and this is probably not wanted, so just using play and setting a playTimeOffset is preferred, something like this:

```js
player.play({ whichSound: SOUND_ID, playTimeOffset: 10 }) // plays a certain song and start at 10 seconds
```

I also added documentation for all player functions, so it should now be easier to get an idea of what the player is capable off doing

I guess this answers your feature request, so I will close this ticket, if however I missed something, then please open a new ticket and I will try to look into it as quickly as I can
